version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "3000:3000"
      - "9229:9229"
    privileged: true
    environment:
      - NODE_ENV=development
      - DISPLAY=${DISPLAY}
      - DEBUG=*
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/ttyUSB3:/dev/ttyUSB3
    command: npm run dev:debug

  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:watch
    environment:
      - NODE_ENV=test

  lint:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run lint:watch 